---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: servico-inscricao
  title: servico-inscricao
  description: Serviço responsável por gerenciamento das informações do processo de inscrição..
  annotations:
    gitlab.com/project-id: "3035"
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    sonarqube.org/project-key: servico-inscricao
  tags:
    - dotnet
    - csharp
spec:
  type: service
  owner: group:default/squad-exponencial
  lifecycle: production
  system: backstage-system
  dependsOn: []
  providesApis:
    - servico-inscricao-api
  consumesApis: []
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: servico-inscricao-location
spec:
  targets:
    - ./catalog/apis/servico-inscricao-api/catalog-info.yaml
