START TRANSACTION;

CREATE TABLE "Campus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Campus" PRIMARY KEY ("Id")
);

CREATE TABLE "Concurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "PeriodoLetivo" character varying(10) NOT NULL,
    "InicioInscricao" timestamp with time zone NOT NULL,
    "TerminoInscricao" timestamp with time zone NOT NULL,
    "InicioProva" timestamp with time zone,
    "TerminoProva" timestamp with time zone,
    "DivulgacaoResultado" timestamp with time zone,
    "SolicitaAnoInscricaoEnem" boolean,
    "ExigeAceiteDeferimento" boolean,
    "RecebeDocumentoConclusaoEnsinoSuperior" boolean,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Concurso" PRIMARY KEY ("Id")
);

CREATE TABLE "Configuracao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChaveGenerica" character varying(150) NOT NULL,
    "Valor" character varying(500) NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_Configuracao" PRIMARY KEY ("Id")
);

CREATE TABLE "EtapaTemplate" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descricao" character varying(200) NOT NULL,
    "NomeArquivo" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_EtapaTemplate" PRIMARY KEY ("Id")
);

CREATE TABLE "Ficha" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descricao" character varying(200) NOT NULL,
    "Padrao" boolean NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Ficha" PRIMARY KEY ("Id")
);

CREATE TABLE "FormaEntrada" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descricao" character varying(255),
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_FormaEntrada" PRIMARY KEY ("Id")
);

CREATE TABLE "Instituicao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Sigla" character varying(50) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Instituicao" PRIMARY KEY ("Id")
);

CREATE TABLE "Intake" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    "VigenciaInicio" timestamp with time zone NOT NULL,
    "VigenciaTermino" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Intake" PRIMARY KEY ("Id")
);

CREATE TABLE "Modalidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Descricao" character varying(255),
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Modalidade" PRIMARY KEY ("Id")
);

CREATE TABLE "Pais" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Sigla" character varying(10) NOT NULL,
    "SiglaAbreviada" character varying(10) NOT NULL,
    "Tipo" character varying(1),
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Pais" PRIMARY KEY ("Id")
);

CREATE TABLE "SistemaIntegracao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_SistemaIntegracao" PRIMARY KEY ("Id")
);

CREATE TABLE "TipoFormacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_TipoFormacao" PRIMARY KEY ("Id")
);

CREATE TABLE "Turno" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Turno" PRIMARY KEY ("Id")
);

CREATE TABLE "EtapaFicha" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EtapaTemplateId" integer NOT NULL,
    "Sequencia" integer NOT NULL,
    "FichaId" integer NOT NULL,
    CONSTRAINT "PK_EtapaFicha" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EtapaFicha_EtapaTemplate_EtapaTemplateId" FOREIGN KEY ("EtapaTemplateId") REFERENCES "EtapaTemplate" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EtapaFicha_Ficha_FichaId" FOREIGN KEY ("FichaId") REFERENCES "Ficha" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoCandidato" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FichaId" integer NOT NULL,
    "OfertaId" integer,
    "OfertaConcursoId" integer,
    "CandidatoNome" character varying(100) NOT NULL,
    "CandidatoDataNascimento" timestamp with time zone,
    "CandidatoSexo" integer,
    "CandidatoNecessidadeEspecial" boolean,
    "CandidatoNomeSocial" character varying(100),
    "VoucherCodigo" character varying(50) NOT NULL,
    "VoucherValidado" boolean NOT NULL,
    "Origem" integer NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_InscricaoCandidato" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoCandidato_Ficha_FichaId" FOREIGN KEY ("FichaId") REFERENCES "Ficha" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConcursoFormaEntrada" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormaEntradaId" integer NOT NULL,
    "ConcursoId" integer NOT NULL,
    CONSTRAINT "PK_ConcursoFormaEntrada" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConcursoFormaEntrada_Concurso_ConcursoId" FOREIGN KEY ("ConcursoId") REFERENCES "Concurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConcursoFormaEntrada_FormaEntrada_FormaEntradaId" FOREIGN KEY ("FormaEntradaId") REFERENCES "FormaEntrada" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConcursoModalidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ModalidadeId" integer NOT NULL,
    "ConcursoId" integer NOT NULL,
    CONSTRAINT "PK_ConcursoModalidade" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConcursoModalidade_Concurso_ConcursoId" FOREIGN KEY ("ConcursoId") REFERENCES "Concurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConcursoModalidade_Modalidade_ModalidadeId" FOREIGN KEY ("ModalidadeId") REFERENCES "Modalidade" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Estado" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Sigla" character varying(10) NOT NULL,
    "PaisId" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Estado" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Estado_Pais_PaisId" FOREIGN KEY ("PaisId") REFERENCES "Pais" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoCampus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "CampusId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoCampus" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoCampus_Campus_CampusId" FOREIGN KEY ("CampusId") REFERENCES "Campus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoCampus_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoConcurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "ConcursoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoConcurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoConcurso_Concurso_ConcursoId" FOREIGN KEY ("ConcursoId") REFERENCES "Concurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoConcurso_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoFormaEntrada" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "FormaEntradaId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoFormaEntrada" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoFormaEntrada_FormaEntrada_FormaEntradaId" FOREIGN KEY ("FormaEntradaId") REFERENCES "FormaEntrada" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoFormaEntrada_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoInstituicao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "InstituicaoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoInstituicao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoInstituicao_Instituicao_InstituicaoId" FOREIGN KEY ("InstituicaoId") REFERENCES "Instituicao" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoInstituicao_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoIntake" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "IntakeId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoIntake" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoIntake_Intake_IntakeId" FOREIGN KEY ("IntakeId") REFERENCES "Intake" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoIntake_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoModalidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "ModalidadeId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoModalidade" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoModalidade_Modalidade_ModalidadeId" FOREIGN KEY ("ModalidadeId") REFERENCES "Modalidade" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoModalidade_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoPais" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "PaisId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoPais" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoPais_Pais_PaisId" FOREIGN KEY ("PaisId") REFERENCES "Pais" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoPais_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConcursoTipoFormacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TipoFormacaoId" integer NOT NULL,
    "ConcursoId" integer NOT NULL,
    CONSTRAINT "PK_ConcursoTipoFormacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConcursoTipoFormacao_Concurso_ConcursoId" FOREIGN KEY ("ConcursoId") REFERENCES "Concurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConcursoTipoFormacao_TipoFormacao_TipoFormacaoId" FOREIGN KEY ("TipoFormacaoId") REFERENCES "TipoFormacao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Curso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    "ModalidadeId" integer NOT NULL,
    "TipoFormacaoId" integer NOT NULL,
    CONSTRAINT "PK_Curso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Curso_Modalidade_ModalidadeId" FOREIGN KEY ("ModalidadeId") REFERENCES "Modalidade" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Curso_TipoFormacao_TipoFormacaoId" FOREIGN KEY ("TipoFormacaoId") REFERENCES "TipoFormacao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoTipoFormacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "TipoFormacaoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoTipoFormacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoTipoFormacao_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoTipoFormacao_TipoFormacao_TipoFormacaoId" FOREIGN KEY ("TipoFormacaoId") REFERENCES "TipoFormacao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoTurno" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "TurnoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoTurno" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoTurno_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoTurno_Turno_TurnoId" FOREIGN KEY ("TurnoId") REFERENCES "Turno" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EtapasInscricao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "EtapaFichaId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "Atual" boolean NOT NULL,
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_EtapasInscricao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EtapasInscricao_InscricaoCandidato_InscricaoCandidatoId" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoContato" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "Valor" character varying(100) NOT NULL,
    "ValorFormatado" character varying(150) NOT NULL,
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_InscricaoContato" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoContato_InscricaoCandidato_InscricaoCandidatoId" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoDocumentacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Observacoes" text,
    "TipoDocumento" integer NOT NULL,
    "Nome" character varying(100),
    "Extensao" character varying(10),
    "Tamanho" integer,
    "LocalArquivo" character varying(200),
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_InscricaoDocumentacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoDocumentacao_InscricaoCandidato_InscricaoCandidato~" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoDocumentos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Valor" character varying(100) NOT NULL,
    "ValorFormatado" character varying(150) NOT NULL,
    "Tipo" integer NOT NULL,
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_InscricaoDocumentos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoDocumentos_InscricaoCandidato_InscricaoCandidatoId" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoEndereco" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "Cep" character varying(50) NOT NULL,
    "Rua" character varying(150) NOT NULL,
    "Numero" character varying(150) NOT NULL,
    "Complemento" character varying(150),
    "Bairro" character varying(150) NOT NULL,
    "Cidade" character varying(150) NOT NULL,
    "Estado" character varying(150) NOT NULL,
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_InscricaoEndereco" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoEndereco_InscricaoCandidato_InscricaoCandidatoId" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "InscricaoSeguroFianca" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "NomeFiador" character varying(100),
    "TipoRelacionamentoSegurado" text,
    "PercentualFiador" numeric,
    "RendaMediaMensal" numeric,
    "TipoDocumento" integer NOT NULL,
    "DocumentoValor" character varying(100),
    "DocumentoValorFormatado" character varying(150),
    "TipoContato" integer NOT NULL,
    "ContatoValor" character varying(100),
    "ContatoValorFormatado" character varying(150),
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_InscricaoSeguroFianca" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InscricaoSeguroFianca_InscricaoCandidato_InscricaoCandidato~" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StatusInscricao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Tipo" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "Atual" boolean NOT NULL,
    "InscricaoCandidatoId" integer NOT NULL,
    CONSTRAINT "PK_StatusInscricao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StatusInscricao_InscricaoCandidato_InscricaoCandidatoId" FOREIGN KEY ("InscricaoCandidatoId") REFERENCES "InscricaoCandidato" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Cidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(100) NOT NULL,
    "CodigoMunicipio" integer,
    "Ddd" integer,
    "EstadoId" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Cidade" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cidade_Estado_EstadoId" FOREIGN KEY ("EstadoId") REFERENCES "Estado" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoEstado" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "EstadoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoEstado" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoEstado_Estado_EstadoId" FOREIGN KEY ("EstadoId") REFERENCES "Estado" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoEstado_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoCurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "CursoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoCurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoCurso_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES "Curso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoCurso_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Produto" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InstituicaoId" integer NOT NULL,
    "CampusId" integer NOT NULL,
    "CursoId" integer NOT NULL,
    "TurnoId" integer NOT NULL,
    "Sku" character varying(255) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Produto" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produto_Campus_CampusId" FOREIGN KEY ("CampusId") REFERENCES "Campus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Produto_Curso_CursoId" FOREIGN KEY ("CursoId") REFERENCES "Curso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Produto_Instituicao_InstituicaoId" FOREIGN KEY ("InstituicaoId") REFERENCES "Instituicao" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Produto_Turno_TurnoId" FOREIGN KEY ("TurnoId") REFERENCES "Turno" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Escola" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(200) NOT NULL,
    "CodigoInep" integer NOT NULL,
    "CidadeId" integer NOT NULL,
    "CodigoTipoEscola" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Escola" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Escola_Cidade_CidadeId" FOREIGN KEY ("CidadeId") REFERENCES "Cidade" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoCidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "CidadeId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoCidade" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoCidade_Cidade_CidadeId" FOREIGN KEY ("CidadeId") REFERENCES "Cidade" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoCidade_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoProduto" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "ProdutoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoProduto" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoProduto_Produto_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produto" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoProduto_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Oferta" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProdutoId" integer NOT NULL,
    "IntakeId" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_Oferta" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Oferta_Intake_IntakeId" FOREIGN KEY ("IntakeId") REFERENCES "Intake" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Oferta_Produto_ProdutoId" FOREIGN KEY ("ProdutoId") REFERENCES "Produto" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoEscola" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "EscolaId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoEscola" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoEscola_Escola_EscolaId" FOREIGN KEY ("EscolaId") REFERENCES "Escola" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoEscola_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoOferta" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "OfertaId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoOferta" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoOferta_Oferta_OfertaId" FOREIGN KEY ("OfertaId") REFERENCES "Oferta" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoOferta_SistemaIntegracao_IntegracaoSistemaId" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OfertaConcurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ConcursoId" integer NOT NULL,
    "OfertaId" integer NOT NULL,
    "Ativo" boolean NOT NULL,
    "Key" uuid NOT NULL,
    "CriadoEm" timestamp with time zone,
    "AlteradoEm" timestamp with time zone,
    CONSTRAINT "PK_OfertaConcurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OfertaConcurso_Concurso_ConcursoId" FOREIGN KEY ("ConcursoId") REFERENCES "Concurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OfertaConcurso_Oferta_OfertaId" FOREIGN KEY ("OfertaId") REFERENCES "Oferta" ("Id") ON DELETE CASCADE
);

CREATE TABLE "IntegracaoOfertaConcurso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IntegracaoSistemaId" integer NOT NULL,
    "CodigoOrigem" character varying(100) NOT NULL,
    "OfertaConcursoId" integer NOT NULL,
    CONSTRAINT "PK_IntegracaoOfertaConcurso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_IntegracaoOfertaConcurso_OfertaConcurso_OfertaConcursoId" FOREIGN KEY ("OfertaConcursoId") REFERENCES "OfertaConcurso" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_IntegracaoOfertaConcurso_SistemaIntegracao_IntegracaoSistem~" FOREIGN KEY ("IntegracaoSistemaId") REFERENCES "SistemaIntegracao" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cidade_EstadoId" ON "Cidade" ("EstadoId");

CREATE INDEX "IX_ConcursoFormaEntrada_ConcursoId" ON "ConcursoFormaEntrada" ("ConcursoId");

CREATE INDEX "IX_ConcursoFormaEntrada_FormaEntradaId" ON "ConcursoFormaEntrada" ("FormaEntradaId");

CREATE INDEX "IX_ConcursoModalidade_ConcursoId" ON "ConcursoModalidade" ("ConcursoId");

CREATE INDEX "IX_ConcursoModalidade_ModalidadeId" ON "ConcursoModalidade" ("ModalidadeId");

CREATE INDEX "IX_ConcursoTipoFormacao_ConcursoId" ON "ConcursoTipoFormacao" ("ConcursoId");

CREATE INDEX "IX_ConcursoTipoFormacao_TipoFormacaoId" ON "ConcursoTipoFormacao" ("TipoFormacaoId");

CREATE INDEX "IX_Curso_ModalidadeId" ON "Curso" ("ModalidadeId");

CREATE INDEX "IX_Curso_TipoFormacaoId" ON "Curso" ("TipoFormacaoId");

CREATE INDEX "IX_Escola_CidadeId" ON "Escola" ("CidadeId");

CREATE INDEX "IX_Estado_PaisId" ON "Estado" ("PaisId");

CREATE INDEX "IX_EtapaFicha_EtapaTemplateId" ON "EtapaFicha" ("EtapaTemplateId");

CREATE INDEX "IX_EtapaFicha_FichaId" ON "EtapaFicha" ("FichaId");

CREATE INDEX "IX_EtapasInscricao_InscricaoCandidatoId" ON "EtapasInscricao" ("InscricaoCandidatoId");

CREATE INDEX "IX_InscricaoCandidato_FichaId" ON "InscricaoCandidato" ("FichaId");

CREATE INDEX "IX_InscricaoContato_InscricaoCandidatoId" ON "InscricaoContato" ("InscricaoCandidatoId");

CREATE INDEX "IX_InscricaoDocumentacao_InscricaoCandidatoId" ON "InscricaoDocumentacao" ("InscricaoCandidatoId");

CREATE INDEX "IX_InscricaoDocumentos_InscricaoCandidatoId" ON "InscricaoDocumentos" ("InscricaoCandidatoId");

CREATE INDEX "IX_InscricaoEndereco_InscricaoCandidatoId" ON "InscricaoEndereco" ("InscricaoCandidatoId");

CREATE INDEX "IX_InscricaoSeguroFianca_InscricaoCandidatoId" ON "InscricaoSeguroFianca" ("InscricaoCandidatoId");

CREATE UNIQUE INDEX "IX_IntegracaoCampus_CampusId" ON "IntegracaoCampus" ("CampusId");

CREATE INDEX "IX_IntegracaoCampus_IntegracaoSistemaId" ON "IntegracaoCampus" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoCidade_CidadeId" ON "IntegracaoCidade" ("CidadeId");

CREATE INDEX "IX_IntegracaoCidade_IntegracaoSistemaId" ON "IntegracaoCidade" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoConcurso_ConcursoId" ON "IntegracaoConcurso" ("ConcursoId");

CREATE INDEX "IX_IntegracaoConcurso_IntegracaoSistemaId" ON "IntegracaoConcurso" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoCurso_CursoId" ON "IntegracaoCurso" ("CursoId");

CREATE INDEX "IX_IntegracaoCurso_IntegracaoSistemaId" ON "IntegracaoCurso" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoEscola_EscolaId" ON "IntegracaoEscola" ("EscolaId");

CREATE INDEX "IX_IntegracaoEscola_IntegracaoSistemaId" ON "IntegracaoEscola" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoEstado_EstadoId" ON "IntegracaoEstado" ("EstadoId");

CREATE INDEX "IX_IntegracaoEstado_IntegracaoSistemaId" ON "IntegracaoEstado" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoFormaEntrada_FormaEntradaId" ON "IntegracaoFormaEntrada" ("FormaEntradaId");

CREATE INDEX "IX_IntegracaoFormaEntrada_IntegracaoSistemaId" ON "IntegracaoFormaEntrada" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoInstituicao_InstituicaoId" ON "IntegracaoInstituicao" ("InstituicaoId");

CREATE INDEX "IX_IntegracaoInstituicao_IntegracaoSistemaId" ON "IntegracaoInstituicao" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoIntake_IntakeId" ON "IntegracaoIntake" ("IntakeId");

CREATE INDEX "IX_IntegracaoIntake_IntegracaoSistemaId" ON "IntegracaoIntake" ("IntegracaoSistemaId");

CREATE INDEX "IX_IntegracaoModalidade_IntegracaoSistemaId" ON "IntegracaoModalidade" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoModalidade_ModalidadeId" ON "IntegracaoModalidade" ("ModalidadeId");

CREATE INDEX "IX_IntegracaoOferta_IntegracaoSistemaId" ON "IntegracaoOferta" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoOferta_OfertaId" ON "IntegracaoOferta" ("OfertaId");

CREATE INDEX "IX_IntegracaoOfertaConcurso_IntegracaoSistemaId" ON "IntegracaoOfertaConcurso" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoOfertaConcurso_OfertaConcursoId" ON "IntegracaoOfertaConcurso" ("OfertaConcursoId");

CREATE INDEX "IX_IntegracaoPais_IntegracaoSistemaId" ON "IntegracaoPais" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoPais_PaisId" ON "IntegracaoPais" ("PaisId");

CREATE INDEX "IX_IntegracaoProduto_IntegracaoSistemaId" ON "IntegracaoProduto" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoProduto_ProdutoId" ON "IntegracaoProduto" ("ProdutoId");

CREATE INDEX "IX_IntegracaoTipoFormacao_IntegracaoSistemaId" ON "IntegracaoTipoFormacao" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoTipoFormacao_TipoFormacaoId" ON "IntegracaoTipoFormacao" ("TipoFormacaoId");

CREATE INDEX "IX_IntegracaoTurno_IntegracaoSistemaId" ON "IntegracaoTurno" ("IntegracaoSistemaId");

CREATE UNIQUE INDEX "IX_IntegracaoTurno_TurnoId" ON "IntegracaoTurno" ("TurnoId");

CREATE INDEX "IX_Oferta_IntakeId" ON "Oferta" ("IntakeId");

CREATE INDEX "IX_Oferta_ProdutoId" ON "Oferta" ("ProdutoId");

CREATE INDEX "IX_OfertaConcurso_ConcursoId" ON "OfertaConcurso" ("ConcursoId");

CREATE INDEX "IX_OfertaConcurso_OfertaId" ON "OfertaConcurso" ("OfertaId");

CREATE INDEX "IX_Produto_CampusId" ON "Produto" ("CampusId");

CREATE INDEX "IX_Produto_CursoId" ON "Produto" ("CursoId");

CREATE INDEX "IX_Produto_InstituicaoId" ON "Produto" ("InstituicaoId");

CREATE INDEX "IX_Produto_TurnoId" ON "Produto" ("TurnoId");

CREATE INDEX "IX_StatusInscricao_InscricaoCandidatoId" ON "StatusInscricao" ("InscricaoCandidatoId");

COMMIT;