DROP INDEX IF EXISTS "IX_IntegracaoInstituicao_InstituicaoId" ;

INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '1',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '1'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '8',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '5'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '7',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '4'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '5',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '3'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '9',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '6'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '10',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '7'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '11',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '9'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '12',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '8'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '13',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '10'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '21',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '11'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '27',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '44'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '58',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '51'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '68',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '72'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '70',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '64'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '71',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '66'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '90',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '87'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '79',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '78'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '80',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '77'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '81',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '90'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '82',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '74'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '91',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '105'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '92',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '106'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '93',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '90'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '94',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '93'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '112',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '39'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '115',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '91'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '122',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '132'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '124',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '99'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '52',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '45'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '28',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '22'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '60',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '54'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '73',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '82'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '74',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '80'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '75',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '81'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '76',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '76'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '77',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '79'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '89',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '101'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '100',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '116'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '113',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '114'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '116',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '153'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '117',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '154'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '118',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '152'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '123',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '159'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '23',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '20'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '24',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '21'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '29',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '23'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '30',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '24'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '31',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '25'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '32',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '26'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '33',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '27'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '34',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '28'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '35',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '29'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '36',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '30'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '37',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '31'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '38',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '32'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '39',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '33'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '40',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '34'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '41',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '35'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '42',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '36'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '43',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '37'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '44',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '38'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '45',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '39'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '46',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '40'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '47',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '41'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '48',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '42'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '49',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '43'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '50',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '44'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '56',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '49'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '57',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '50'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '59',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '46'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '69',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '71'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '72',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '57'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '87',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '94'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '88',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '97'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '96',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '70'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '97',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '88'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '101',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '130'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '102',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '126'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '103',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '125'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '104',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '127'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '105',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '128'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '106',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '129'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '107',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '132'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '108',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '133'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '111',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '138'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '114',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '149'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '119',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '92'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '120',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '90'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '121',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '158'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '125',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '166'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '14',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '12'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '15',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '13'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '16',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '15'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '17',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '16'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '18',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '17'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '19',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '18'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '22',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '19'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '53',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '5'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '61',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '65'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '62',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '58'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '63',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '59'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '64',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '60'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '65',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '61'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '66',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '62'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '67',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '63'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '85',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '75'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '86',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '73'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '95',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '107'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '98',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '103'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '99',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '86'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '109',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '135'));
INSERT INTO public."IntegracaoInstituicao"("IntegracaoSistemaId", "CodigoOrigem", "InstituicaoId")
	VALUES ((select "Id" from "SistemaIntegracao" where "Nome" = 'Vestib'), '110',  (select "InstituicaoId" from public."IntegracaoInstituicao" ii inner join "Instituicao" i on i."Id" = ii."InstituicaoId" where i."Ativo" = true and ii."IntegracaoSistemaId" = (select "Id" from "SistemaIntegracao" where "Nome" = 'SIAF') and "CodigoOrigem" = '136'));