using ArchUnitNET.xUnit;
using Xunit;

using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace Anima.Inscricao.ArchTests.Repositories;

public class NomesObjetosTest
{
    private const string NOME_OBJETO = "Repository";

    [Fact]
    public void DeveValidarQueContratosDeRepositoriosPossuemONomeCorreto()
    {
        var padraoNomeRegex = ObterRegexInterfaces();
        var interfaces = Interfaces().That().HaveFullNameContaining(NOME_OBJETO);

        var regraInterfaces = interfaces
            .Should().HaveFullName(padraoNomeRegex, true);

        regraInterfaces.Check(Config.Arquitetura);
    }

    [Fact]
    public void DeveValidarQueImplementacoesDeRepositoriosPossuemONomeCorreto()
    {
        var padraoNomeRegex = ObterRegexInterfaces();
        var classes = Classes().That().ImplementInterface(padraoNomeRegex, true);

        var regraClasses = classes
            .Should().HaveFullNameContaining(NOME_OBJETO)
            .OrShould().HaveNameStartingWith("AutoGenerated");

        regraClasses.Check(Config.Arquitetura);
    }

    private static string ObterRegexInterfaces() => Config.ObterRegexInterfaces(NOME_OBJETO);
}
