using ArchUnitNET.xUnit;

using static ArchUnitNET.Fluent.ArchRuleDefinition;

namespace Anima.Inscricao.ArchTests.Repositories;

public class CamadasObjetosTest
{
    [Fact]
    public void DeveValidarQueContratosDeRepositoriosEstaoNaCamadaDeDominioOuAplicacao()
    {
        var interfaces = Interfaces().That().HaveNameContaining("Repository");

        var regraInterfaces = interfaces
            .Should().Be(Config.CamadaDominio).OrShould().Be(Config.CamadaAplicacao);

        regraInterfaces.Check(Config.Arquitetura);
    }

    [Fact]
    public void DeveValidarQueImplementacoesDeRepositoriosEstaoNaCamadaDeData()
    {
        var interfaces = Interfaces().That().HaveNameContaining("Repository");
        var classes = Classes().That().AreAssignableTo(interfaces);

        var regraClasses = classes
            .Should().Be(Config.CamadaData)
            .OrShould().HaveNameStartingWith("AutoGenerated");

        regraClasses.Check(Config.Arquitetura);
    }
}
